### Endpoint de teste
GET http://localhost:3003/ping


//--------------------  Endpoints Turmas

### Buscar turmas 
GET http://localhost:3003/all/turmas

### Criar Turma
POST http://localhost:3003/criar/turma
Content-Type: application/json

{

"nome": "teste", 
"modulo": 5
}

### Mudar Módulo da Turma
PUT http://localhost:3003/turmas
Content-Type: application/json

{
"id" : "1671202148443",
"modulo": 4
}

//-------------------- Endpoints Estudantes

### Buscar por nome o Estudante
GET http://localhost:3003/estudante?nome=santiago


### Buscar todos os Estudantes
GET http://localhost:3003/all/estudante

### Criar Estudante 
POST http://localhost:3003/criar/estudante
Content-Type: application/json

{
"nome": "Bob Esponja", 
"email": "bobesponja@gmail.com", 
"data_nasc": "1999-05-01", 
"turma_id": "001",
"hobby": "comer"
}

// Mudar Estudante de turma 
### 
PUT http://localhost:3003/estudante
Content-Type: application/json

{
"id" : "001",
"turma_id" : "001"
}

//-------------------- Endpoints Docentes

### Buscar todos os Docentes 
GET http://localhost:3003/all/docentes

### Criar Docente 
POST http://localhost:3003/criar/docente 
Content-Type: application/json

{
"nome": "teste", 
"email": "teste3@gmail.com", 
"data_nasc": "1995-02-10", 
"turma_id": "001"
}

// Mudar docente de turma 
### 
PUT http://localhost:3003/docentes
Content-Type: application/json

{
"id" : "1671118031003",
"turma_id" : "002"
}